name: build and release
on:
  push:
    branches:
      - master

jobs:
  maven-build:
    name: Maven build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
          cache: maven

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: npm
          cache-dependency-path: src/main/client/package-lock.json

      - name: unit tests
        run: mvn -B test --file pom.xml

      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/report-viewer-0.0.1-SNAPSHOT.jar

  docker-push:
    name: Docker push
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - maven-build
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: jar
          path: target

      - name: Version Increment
        uses: reecetech/version-increment@2024.4.4
        id: version
        with:
          scheme: semver
          increment: patch

      - name: build the docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.version.outputs.version }}

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.version.outputs.version }}

  release:
    name: Github release
    runs-on: ubuntu-latest
    needs:
      - docker-push
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ jobs.docker-push.outputs.version }}